name: Generate Pacman Chart

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Chart
      run: |
        curl -s -o pacman-contribution-graph.svg "https://ghchart.rshah.org/danmoribe"
        cp pacman-contribution-graph.svg pacman-contribution-graph-dark.svg
        echo "Files created:"
        ls -la *.svg

    - name: Push to Output Branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git checkout --orphan output
        git rm -rf .
        cp ../pacman-contribution-graph.svg ./
        cp ../pacman-contribution-graph.svg ./pacman-contribution-graph-dark.svg
        git add *.svg
        git commit -m "Update Pacman chart"
        git push origin output --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
